Repository COSC481W-2022Fall/capstone-project-vibe, pull requests merged in 2022-12, with the labels that each got.

#99 88 deleting conversation
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/vibe/ChatLog.java
  app/src/main/java/com/example/vibe/ChatsAdapter.java
  app/src/main/res/layout/layout_chat_adapter.xml
Labels: enhancement, Sprint 3

#101 bug: Fix image views to use storage reference instead of url
  app/src/main/java/com/example/vibe/ChatsAdapter.java
  app/src/main/java/com/example/vibe/SearchAdapter.java
  app/src/main/java/com/example/vibe/Settings_View.java
Labels: bug, Sprint 3

#102 61 design
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/background_left.xml
  app/src/main/res/drawable/background_mdpi.png
  app/src/main/res/drawable/background_right.xml
  app/src/main/res/drawable/customborder.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_chat_log.xml
  app/src/main/res/layout/activity_conversation_view.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_settings_view.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/chat_item_left.xml
  app/src/main/res/layout/chat_item_right.xml
  app/src/main/res/layout/layout_chat_adapter.xml
  app/src/main/res/layout/popup.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, Sprint 2, Sprint 3

#103 86 blocking
  app/src/main/java/com/example/vibe/ChatLog.java
  app/src/main/java/com/example/vibe/ChatsAdapter.java
  app/src/main/java/com/example/vibe/ConversationView.java
  app/src/main/java/com/example/vibe/Login.java
  app/src/main/java/com/example/vibe/Register.java
  app/src/main/res/layout/layout_chat_adapter.xml
  app/src/main/res/layout/popup_user_info.xml
Labels: enhancement, Sprint 3

#104 61 design
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/vibe/ChatLog.java
  app/src/main/java/com/example/vibe/Message.java
  app/src/main/java/com/example/vibe/MessageAdapter.java
  app/src/main/res/layout/activity_chat_log.xml
  app/src/main/res/layout/activity_conversation_view.xml
  app/src/main/res/layout/activity_settings_view.xml
  app/src/main/res/layout/chat_item_left.xml
  app/src/main/res/layout/chat_item_right.xml
  app/src/main/res/layout/layout_chat_adapter.xml
  app/src/main/res/layout/popup.xml
  app/src/main/res/layout/popup_add.xml
  app/src/main/res/layout/popup_user_info.xml
  build.gradle
Labels: bug, enhancement
