Repository COSC481W-2022Fall/capstone-project-vibe, pull requests merged in 2022-11, with the labels that each got.

#76 feature: set icons for each button
  app/src/main/res/drawable/icon.png
  app/src/main/res/layout/activity_chat_log.xml
Labels: enhancement, Sprint 2

#79 Merge branch '27-add-conversation' into testing
  app/src/main/java/com/example/vibe/SearchAdapter.java
Labels: enhancement, Sprint 2

#81 33 conversation
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/vibe/ConversationView.java
  app/src/main/java/com/example/vibe/Message.java
  app/src/main/java/com/example/vibe/MessageAdapter.java
  app/src/main/java/com/example/vibe/Register.java
  app/src/main/java/com/example/vibe/Users.java
Labels: enhancement, Sprint 2

#93 84 settings propic cancel
  app/src/main/java/com/example/vibe/ChangePassword.java
  app/src/main/java/com/example/vibe/Settings_View.java
  app/src/main/res/layout/activity_settings_view.xml
Labels: bug, enhancement

#95 90 conversation on physical device
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/drawable/background_left.xml
  app/src/main/res/drawable/background_right.xml
  app/src/main/res/layout/activity_settings_view.xml
Labels: bug, Sprint 3

#96 89 duplicate conversations
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/vibe/FriendSearch.java
  app/src/main/java/com/example/vibe/SearchAdapter.java
  app/src/main/java/com/example/vibe/UserAdapter.java
  app/src/main/res/layout/activity_friendsearch.xml
Labels: bug, Sprint 3
